import type { Metadata } from "next";
import './layout.scss'
import "./globals.css";
import { Header } from "./Components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="en">
  <body>
    <div className="page-container">
      <div className="background-container">
        <img
          src="/background.png"
          alt="backgroundImage"
          className="background-image"
        />
      </div>
      <div className="overlay-gradient"></div>
      <div className="content-container">
        <Header />
        {children}
      </div>
    </div>
  </body>
</html>

  );
}
